# Generated by Django 2.2 on 2023-05-12 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppInstanceInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appdId', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
