# Generated by Django 2.2 on 2022-08-11 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NsInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsInstanceName', models.TextField()),
                ('nsInstanceDescription', models.TextField()),
                ('nsdId', models.TextField()),
                ('nsdInfoId', models.TextField()),
                ('flavourId', models.TextField(blank=True, null=True)),
                ('nestedNsInstanceId', models.TextField(blank=True, null=True)),
                ('nsState', models.TextField(default='NOT_INSTANTIATED')),
            ],
        ),
    ]
