# Generated by Django 2.2 on 2022-08-12 04:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('NSInstanceManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VnfInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vnfInstanceName', models.TextField(blank=True, null=True)),
                ('vnfInstanceDescription', models.TextField(blank=True, null=True)),
                ('vnfdId', models.TextField()),
                ('vnfProvider', models.TextField()),
                ('vnfProductName', models.TextField()),
                ('vnfSoftwareVersion', models.TextField()),
                ('vnfdVersion', models.TextField()),
                ('vnfPkgId', models.TextField()),
                ('vnfConfigurableProperties', models.TextField(blank=True, null=True)),
                ('vimId', models.TextField(blank=True, null=True)),
                ('instantiationState', models.TextField(default='NOT_INSTANTIATED')),
                ('metadata', models.TextField(blank=True, null=True)),
                ('extensions', models.TextField(blank=True, null=True)),
                ('vnfInstance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='NsInstance_VnfInstance', to='NSInstanceManagement.NsInstance')),
            ],
        ),
    ]
