# Generated by Django 2.2 on 2022-08-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSInstanceManagement', '0002_vnfinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsinstance',
            name='deployedCluster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsinstance',
            name='platformName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
