# Generated by Django 2.2 on 2022-08-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSInstanceManagement', '0003_auto_20220812_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='vnfinstance',
            name='appInfoName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vnfinstance',
            name='appName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
