# Generated by Django 2.2 on 2022-08-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSInstanceManagement', '0004_auto_20220816_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnfinstance',
            name='appInfoName',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vnfinstance',
            name='appName',
            field=models.TextField(),
        ),
    ]
