# Generated by Django 2.2 on 2022-08-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VnfPackageManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vnfpkginfo',
            name='appLatency',
            field=models.TextField(default='100ms'),
        ),
        migrations.AlterField(
            model_name='vnfpkginfo',
            name='virtualComputeDescriptor',
            field=models.TextField(default='512Mi'),
        ),
        migrations.AlterField(
            model_name='vnfpkginfo',
            name='virtualStorageDescriptor',
            field=models.TextField(default='250m'),
        ),
    ]
