# Generated by Django 2.2 on 2023-05-12 08:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('VnfPackageManagement', '0003_auto_20220812_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_package_Id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
