# Generated by Django 2.2 on 2023-06-02 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPkgInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appdId', models.TextField(blank=True, null=True)),
                ('appProvider', models.TextField(blank=True, null=True)),
                ('appProductName', models.TextField(blank=True, null=True)),
                ('appName', models.TextField(blank=True, null=True)),
                ('appSoftwareVersion', models.TextField(blank=True, null=True)),
                ('appdVersion', models.TextField(blank=True, null=True)),
                ('mecVersion', models.TextField(blank=True, null=True)),
                ('appInfoName', models.TextField(blank=True, null=True)),
                ('appDescription', models.TextField(blank=True, null=True)),
                ('swImageDescriptor', models.TextField(blank=True, null=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('virtualComputeDescriptor', models.TextField(default='512Mi')),
                ('virtualStorageDescriptor', models.TextField(default='250m')),
                ('appExtCpd', models.TextField(blank=True, null=True)),
                ('appServiceRequired', models.TextField(blank=True, null=True)),
                ('appServiceOptional', models.TextField(blank=True, null=True)),
                ('appServiceProduced', models.TextField(blank=True, null=True)),
                ('appFeatureRequired', models.TextField(blank=True, null=True)),
                ('appFeatureOptional', models.TextField(blank=True, null=True)),
                ('transportDependencies', models.TextField(blank=True, null=True)),
                ('appTrafficRule', models.TextField(blank=True, null=True)),
                ('appDNSRule', models.TextField(blank=True, null=True)),
                ('appLatency', models.TextField(default='100ms')),
                ('onboardingState', models.TextField(default='CREATED')),
                ('operationalState', models.TextField(default='DISABLED')),
                ('usageState', models.TextField(default='NOT_IN_USE')),
                ('userDefinedData', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NsInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_package_Id', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
