# Generated by Django 2.2 on 2022-08-11 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NsdInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nsdId', models.TextField(blank=True, null=True)),
                ('nsdName', models.TextField(blank=True, null=True)),
                ('nsdVersion', models.TextField(blank=True, null=True)),
                ('nsdDesigner', models.TextField(blank=True, null=True)),
                ('nsdInvariantId', models.TextField(blank=True, null=True)),
                ('vnfPkgIds', models.TextField(blank=True, null=True)),
                ('pnfdInfoIds', models.TextField(blank=True, null=True)),
                ('nestedNsdInfoIds', models.TextField(blank=True, null=True)),
                ('nsdOnboardingState', models.TextField(default='CREATED')),
                ('nsdOperationalState', models.TextField(default='DISABLED')),
                ('nsdUsageState', models.TextField(default='NOT_IN_USE')),
                ('userDefinedData', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
