# Generated by Django 2.2 on 2022-08-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NSManagement', '0002_auto_20220811_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsdinfo',
            name='deployedCluster',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nsdinfo',
            name='platformName',
            field=models.TextField(blank=True, null=True),
        ),
    ]
